services:
  kaede:
    restart: unless-stopped
    env_file:
      - ${ENV_FILE:-./deploy/env.local}
    environment:
      HOST: 0.0.0.0
      PORT: 3000

  nozomi:
    restart: unless-stopped
    env_file:
      - ${ENV_FILE:-./deploy/env.local}
    environment:
      HOST: 0.0.0.0
      PORT: 8000
