/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely'

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>

export type Json = JsonValue

export type JsonArray = JsonValue[]

export type JsonObject = {
  [x: string]: JsonValue | undefined
}

export type JsonPrimitive = boolean | number | string | null

export type JsonValue = JsonArray | JsonObject | JsonPrimitive

export type Timestamp = ColumnType<Date, Date | string, Date | string>

export interface AuthIdentities {
  created_at: Generated<Timestamp>
  email: string
  email_verified: Generated<boolean>
  hosted_domain: string | null
  id: Generated<string>
  provider: string
  provider_subject: string
  updated_at: Generated<Timestamp>
  user_id: string
}

export interface Buildings {
  created_at: Generated<Timestamp>
  id: Generated<string>
  latitude: number | null
  longitude: number | null
  name: string
  organization_id: string
  updated_at: Generated<Timestamp>
}

export interface Floors {
  building_id: string
  created_at: Generated<Timestamp>
  id: Generated<string>
  image_object_path: string
  level: number
  name: string
  organization_id: string
  scale: number | null
  updated_at: Generated<Timestamp>
}

export interface OrganizationCreationRequests {
  created_at: Generated<Timestamp>
  created_organization_id: string | null
  id: Generated<string>
  rejected_reason: string | null
  requested_organization_name: string
  requested_slug: string | null
  requester_user_id: string
  reviewed_at: Timestamp | null
  reviewed_by_user_id: string | null
  status: Generated<string>
  updated_at: Generated<Timestamp>
}

export interface OrganizationInviteRedemptions {
  created_at: Generated<Timestamp>
  email: string
  id: Generated<string>
  invite_id: string
  provider_subject: string
  user_id: string
}

export interface OrganizationInvites {
  created_at: Generated<Timestamp>
  created_by_user_id: string
  email: string
  expires_at: Timestamp
  id: Generated<string>
  max_uses: Generated<number>
  organization_id: string
  revoked_at: Timestamp | null
  role: Generated<string>
  token_hash: string
  updated_at: Generated<Timestamp>
  used_count: Generated<number>
}

export interface OrganizationMemberships {
  created_at: Generated<Timestamp>
  organization_id: string
  role: string
  updated_at: Generated<Timestamp>
  user_id: string
}

export interface Organizations {
  created_at: Generated<Timestamp>
  id: Generated<string>
  name: string
  slug: Generated<string>
  updated_at: Generated<Timestamp>
}

export interface Pedestrians {
  attributes: Generated<Json>
  created_at: Generated<Timestamp>
  display_name: string
  height: number | null
  id: Generated<string>
  organization_id: string
  stride_length: number | null
  updated_at: Generated<Timestamp>
  user_id: string | null
}

export interface Recordings {
  constraints: Generated<Json>
  created_at: Generated<Timestamp>
  deleted_at: Timestamp | null
  floor_id: string
  id: Generated<string>
  organization_id: string
  pedestrian_id: string
  updated_at: Generated<Timestamp>
  upload_status: Generated<string>
  upload_targets: string[]
}

export interface Sessions {
  auth_method: Generated<string>
  created_at: Generated<Timestamp>
  expires_at: Timestamp
  id: Generated<string>
  last_seen_at: Timestamp | null
  revoked_at: Timestamp | null
  session_hash: string
  user_id: string
}

export interface Trajectories {
  constraints: Generated<Json>
  created_at: Generated<Timestamp>
  deleted_at: Timestamp | null
  error_code: string | null
  error_message: string | null
  failed_at: Timestamp | null
  floor_id: string
  id: Generated<string>
  organization_id: string
  recording_id: string
  status: Generated<string>
  updated_at: Generated<Timestamp>
}

export interface UserActivationTokens {
  created_at: Generated<Timestamp>
  created_by_user_id: string
  expires_at: Timestamp
  id: Generated<string>
  organization_id: string
  revoked_at: Timestamp | null
  token_hash: string
  used_at: Timestamp | null
  user_id: string
}

export interface Users {
  created_at: Generated<Timestamp>
  display_name: string
  email: string
  failed_login_attempts: Generated<number>
  global_role: Generated<string>
  id: Generated<string>
  locked_until: Timestamp | null
  password_changed_at: Timestamp | null
  password_hash: string | null
  status: string
  updated_at: Generated<Timestamp>
}

export interface DB {
  auth_identities: AuthIdentities
  buildings: Buildings
  floors: Floors
  organization_creation_requests: OrganizationCreationRequests
  organization_invite_redemptions: OrganizationInviteRedemptions
  organization_invites: OrganizationInvites
  organization_memberships: OrganizationMemberships
  organizations: Organizations
  pedestrians: Pedestrians
  recordings: Recordings
  sessions: Sessions
  trajectories: Trajectories
  user_activation_tokens: UserActivationTokens
  users: Users
}
