/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely'

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>

export type Json = JsonValue

export type JsonArray = JsonValue[]

export type JsonObject = {
  [x: string]: JsonValue | undefined
}

export type JsonPrimitive = boolean | number | string | null

export type JsonValue = JsonArray | JsonObject | JsonPrimitive

export type Timestamp = ColumnType<Date, Date | string, Date | string>

export interface Buildings {
  created_at: Generated<Timestamp>
  id: Generated<string>
  latitude: number | null
  longitude: number | null
  name: string
  organization_id: string | null
  updated_at: Generated<Timestamp>
}

export interface Floors {
  building_id: string
  created_at: Generated<Timestamp>
  id: Generated<string>
  image_object_path: string
  level: number
  name: string
  organization_id: string | null
  scale: number | null
  updated_at: Generated<Timestamp>
}

export interface OrganizationMemberships {
  created_at: Generated<Timestamp>
  organization_id: string
  role: string
  updated_at: Generated<Timestamp>
  user_id: string
}

export interface Organizations {
  created_at: Generated<Timestamp>
  id: Generated<string>
  name: string
  updated_at: Generated<Timestamp>
}

export interface Pedestrians {
  attributes: Generated<Json>
  created_at: Generated<Timestamp>
  display_name: string
  height: number | null
  id: Generated<string>
  organization_id: string | null
  stride_length: number | null
  updated_at: Generated<Timestamp>
  user_id: string | null
}

export interface Recordings {
  created_at: Generated<Timestamp>
  deleted_at: Timestamp | null
  floor_id: string
  id: Generated<string>
  organization_id: string | null
  pedestrian_id: string
  updated_at: Generated<Timestamp>
  upload_status: Generated<string>
  upload_targets: string[]
}

export interface Sessions {
  created_at: Generated<Timestamp>
  expires_at: Timestamp
  id: Generated<string>
  last_seen_at: Timestamp | null
  revoked_at: Timestamp | null
  session_hash: string
  user_id: string
}

export interface Trajectories {
  created_at: Generated<Timestamp>
  deleted_at: Timestamp | null
  error_code: string | null
  error_message: string | null
  failed_at: Timestamp | null
  floor_id: string
  id: Generated<string>
  organization_id: string | null
  recording_id: string
  status: Generated<string>
  updated_at: Generated<Timestamp>
}

export interface TrajectoryConstraints {
  created_at: Generated<Timestamp>
  direction: number | null
  point_type: string
  relative_timestamp: number | null
  seq: number
  trajectory_id: string
  updated_at: Generated<Timestamp>
  x: number
  y: number
}

export interface Users {
  created_at: Generated<Timestamp>
  display_name: string
  email: string
  failed_login_attempts: Generated<number>
  global_role: Generated<string>
  id: Generated<string>
  is_active: Generated<boolean>
  locked_until: Timestamp | null
  password_changed_at: Timestamp | null
  password_hash: string
  password_must_change: Generated<boolean>
  temporary_password_expires_at: Timestamp | null
  updated_at: Generated<Timestamp>
}

export interface DB {
  buildings: Buildings
  floors: Floors
  organization_memberships: OrganizationMemberships
  organizations: Organizations
  pedestrians: Pedestrians
  recordings: Recordings
  sessions: Sessions
  trajectories: Trajectories
  trajectory_constraints: TrajectoryConstraints
  users: Users
}
