/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely'

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>

export type Json = JsonValue

export type JsonArray = JsonValue[]

export type JsonObject = {
  [x: string]: JsonValue | undefined
}

export type JsonPrimitive = boolean | number | string | null

export type JsonValue = JsonArray | JsonObject | JsonPrimitive

export type Timestamp = ColumnType<Date, Date | string, Date | string>

export interface Buildings {
  created_at: Generated<Timestamp>
  id: Generated<string>
  latitude: number | null
  longitude: number | null
  name: string
  updated_at: Generated<Timestamp>
}

export interface Floors {
  building_id: string
  created_at: Generated<Timestamp>
  id: Generated<string>
  image_object_path: string
  level: number
  name: string
  scale: number | null
  updated_at: Generated<Timestamp>
}

export interface Pedestrians {
  attributes: Generated<Json>
  created_at: Generated<Timestamp>
  display_name: string
  height: number | null
  id: Generated<string>
  stride_length: number | null
  updated_at: Generated<Timestamp>
}

export interface Recordings {
  created_at: Generated<Timestamp>
  deleted_at: Timestamp | null
  floor_id: string
  id: Generated<string>
  pedestrian_id: string
  updated_at: Generated<Timestamp>
  upload_status: Generated<string>
  upload_targets: string[]
}

export interface Trajectories {
  created_at: Generated<Timestamp>
  deleted_at: Timestamp | null
  error_code: string | null
  error_message: string | null
  failed_at: Timestamp | null
  floor_id: string
  id: Generated<string>
  recording_id: string
  status: Generated<string>
  updated_at: Generated<Timestamp>
}

export interface TrajectoryConstraints {
  created_at: Generated<Timestamp>
  direction: number | null
  point_type: string
  relative_timestamp: number | null
  seq: number
  trajectory_id: string
  updated_at: Generated<Timestamp>
  x: number
  y: number
}

export interface DB {
  buildings: Buildings
  floors: Floors
  pedestrians: Pedestrians
  recordings: Recordings
  trajectories: Trajectories
  trajectory_constraints: TrajectoryConstraints
}
